language: scala
scala:
  - 2.12.4

script:
  - cd scaladev
  - echo $TRAVIS_SCALA_VERSION
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport &&
    sbt coverageAggregate

after_success:
  sbt coveralls
