language: scala
scala:
  - 2.12.4

script:
  - echo "Scala version:" $TRAVIS_SCALA_VERSION
  - cd scaladev
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport &&
    sbt coverageAggregate

  - cd ../sparkdev
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport &&
    sbt coverageAggregate
